### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [explosion/tokenizations#72]
Problem
---------
On aarch64, `pip install pytokenizations` builds the wheels from source code and then installs it. It requires the user to have a development environment installed on their system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI.

Resolution
-----------
On aarch64, `pip install pytokenizations` should download the wheels from PyPI.

@tamuhey, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by tamuhey** [comment]
@odidev I reverted you PR because the pipeline failed: https://github.com/explosion/tokenizations/runs/4321522590?check_suite_focus=true

Do you have any idea how to solve it?

**Comment by odidev** [comment]
@tamuhey, The issue was that it was uploading the linux_aarch64 wheel to Pypi as well, and it is not supported by Pypi - it supports a Linux AArch64 wheel with tag name manylinux2014_aarch64. I have resolved that issue and raised another PR, kindly review it.
